spring:
  application:
    name: DevOps Metadata Syncer
  main:
    web-application-type: none
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

source:
  github:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}
  enterprise-github:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: devops.metadata.syncer.infrastructure.outbound.database.types
