name: 🚀 Deploy

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  checks:
    name: ✅ Pre-deployment checks
    uses: ./.github/workflows/wf-checks.yaml
    with:
      upload-codecov: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
